# Generated by Django 4.2.7 on 2024-05-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='thumbnail/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
